### ISSUE TITLE
already reported, skipping incident creation

### ISSUE THREAD

**Issue by DanielWeeber** [oxyno-zeta/prometheus-cachethq#10]
Hey,

thank you for this middleware!

When any services goes down once its working fine. When it goes down a second time its showing that its already reported.. but cachet wasn't showing any errors before or anything similar.

`level=info ts=2021-12-29T21:18:32.081495003Z caller=main.go:211 msg="Alert=Newsletter-Tool Name nicht erreichbar. already reported, skipping incident creation."`

**Comment by DanielWeeber** [comment]
I just changed the alert name and it seems to work again, also with subsequent incidents. Very strange..

**Comment by oxyno-zeta** [comment]
Hello @DanielWeeber !

You are welcome. Happy to see that other people are using it :)

I'm not sure I understood completely the problem here. Where this is coming from ? From Alertmanager ? Can you describe me a complete scenario please ?

Regards,
