### ISSUE TITLE
Communincate with cachethq over https

### ISSUE THREAD

**Issue by jeff-byte** [oxyno-zeta/prometheus-cachethq#8]
**Describe the bug**
I would like to communicate with my cachethq over HTTPS but It seems it's not possible to check the certificat or disable this verification, isn't it?

**To Reproduce**
1. https://cachethq/
2. See error
"X509: cannot validate the certificat for x.x.x.x because it's doesn't contain any IP SANs"
 
**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Additional context**

**Comment by oxyno-zeta** [comment]
Hello @jeff-byte ,

Thanks for this issue. I have a question for you.

Your CachetHQ instance is behind a Self Signed Certificate or a certificate coming from AWS, Google or any other ?
I must admit that I never though about this case so if the HTTP client need to be configured, yes this isn't possible for the moment :).

Thanks for your answer.

Regards,

Oxyno-zeta

**Comment by jeff-byte** [comment]
Hello @oxyno-zeta,

Thanks for your return!

In fact my CachetHQ instance is behind a reverse proxy (NGINX) with a certificat signed by my own CA.

The issue came from my cahethq certificat. Without name resolution, I must to provide the IP (subject_alt_name: "IP:xx.xx.xx.xx") and also install the CA.crt on the machine where run prometheus-cachethq.

And now it works perfecly! :-)

I hope my explanations are clear! 

Thanks again!

Regards,

jeff-byte

**Comment by oxyno-zeta** [comment]
Hello @jeff-byte , 

Yes that's what I was about to say :). If you have a private CA, the solution is to put it in the system where you run the app. If you are using the docker image, create a new one with this CA in and this will work like a charm.

The issue can be closed no ?

Regards,

Oxyno-zeta

**Comment by jeff-byte** [comment]
Yes thanks!

**Comment by oxyno-zeta** [comment]
You are welcome. Enjoy :)
